package utfpr.edu.br.controleestoque.vo;
// Generated 22/11/2016 00:32:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int idcompra;
     private Fornecedor fornecedor;
     private Funcionario funcionario;
     private BigDecimal valorcompra;
     private Date criacaocompra;
     private Set itemcompras = new HashSet(0);
     private Set pagamentos = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int idcompra) {
        this.idcompra = idcompra;
    }
    public Compra(int idcompra, Fornecedor fornecedor, Funcionario funcionario, BigDecimal valorcompra, Date criacaocompra, Set itemcompras, Set pagamentos) {
       this.idcompra = idcompra;
       this.fornecedor = fornecedor;
       this.funcionario = funcionario;
       this.valorcompra = valorcompra;
       this.criacaocompra = criacaocompra;
       this.itemcompras = itemcompras;
       this.pagamentos = pagamentos;
    }
   
    public int getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(int idcompra) {
        this.idcompra = idcompra;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public BigDecimal getValorcompra() {
        return this.valorcompra;
    }
    
    public void setValorcompra(BigDecimal valorcompra) {
        this.valorcompra = valorcompra;
    }
    public Date getCriacaocompra() {
        return this.criacaocompra;
    }
    
    public void setCriacaocompra(Date criacaocompra) {
        this.criacaocompra = criacaocompra;
    }
    public Set getItemcompras() {
        return this.itemcompras;
    }
    
    public void setItemcompras(Set itemcompras) {
        this.itemcompras = itemcompras;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }




}


