package utfpr.edu.br.controleestoque.vo;
// Generated 22/11/2016 00:32:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int idfornecedor;
     private String nomefornecedor;
     private String razaosocialpessoajuridica;
     private String cnpjpessoajuridica;
     private String endereco;
     private String cep;
     private String complemento;
     private String numeroendereco;
     private String cidade;
     private String bairro;
     private String estado;
     private String emailcontato;
     private String telefonecontato;
     private String celularcontato;
     private Set compras = new HashSet(0);
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int idfornecedor) {
        this.idfornecedor = idfornecedor;
    }
    public Fornecedor(int idfornecedor, String nomefornecedor, String razaosocialpessoajuridica, String cnpjpessoajuridica, String endereco, String cep, String complemento, String numeroendereco, String cidade, String bairro, String estado, String emailcontato, String telefonecontato, String celularcontato, Set compras, Set produtos) {
       this.idfornecedor = idfornecedor;
       this.nomefornecedor = nomefornecedor;
       this.razaosocialpessoajuridica = razaosocialpessoajuridica;
       this.cnpjpessoajuridica = cnpjpessoajuridica;
       this.endereco = endereco;
       this.cep = cep;
       this.complemento = complemento;
       this.numeroendereco = numeroendereco;
       this.cidade = cidade;
       this.bairro = bairro;
       this.estado = estado;
       this.emailcontato = emailcontato;
       this.telefonecontato = telefonecontato;
       this.celularcontato = celularcontato;
       this.compras = compras;
       this.produtos = produtos;
    }
   
    public int getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(int idfornecedor) {
        this.idfornecedor = idfornecedor;
    }
    public String getNomefornecedor() {
        return this.nomefornecedor;
    }
    
    public void setNomefornecedor(String nomefornecedor) {
        this.nomefornecedor = nomefornecedor;
    }
    public String getRazaosocialpessoajuridica() {
        return this.razaosocialpessoajuridica;
    }
    
    public void setRazaosocialpessoajuridica(String razaosocialpessoajuridica) {
        this.razaosocialpessoajuridica = razaosocialpessoajuridica;
    }
    public String getCnpjpessoajuridica() {
        return this.cnpjpessoajuridica;
    }
    
    public void setCnpjpessoajuridica(String cnpjpessoajuridica) {
        this.cnpjpessoajuridica = cnpjpessoajuridica;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getNumeroendereco() {
        return this.numeroendereco;
    }
    
    public void setNumeroendereco(String numeroendereco) {
        this.numeroendereco = numeroendereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getEmailcontato() {
        return this.emailcontato;
    }
    
    public void setEmailcontato(String emailcontato) {
        this.emailcontato = emailcontato;
    }
    public String getTelefonecontato() {
        return this.telefonecontato;
    }
    
    public void setTelefonecontato(String telefonecontato) {
        this.telefonecontato = telefonecontato;
    }
    public String getCelularcontato() {
        return this.celularcontato;
    }
    
    public void setCelularcontato(String celularcontato) {
        this.celularcontato = celularcontato;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


