package utfpr.edu.br.controleestoque.vo;
// Generated 22/11/2016 00:32:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int idfuncionario;
     private String nomefuncionario;
     private String cargofuncionario;
     private String emailcontato;
     private String telefone;
     private String celular;
     private Date criacaofuncionario;
     private Set pagamentos = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Set recebimentos = new HashSet(0);
     private Set compras = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public Funcionario(int idfuncionario, String nomefuncionario, String cargofuncionario, String emailcontato, String telefone, String celular, Date criacaofuncionario, Set pagamentos, Set vendas, Set recebimentos, Set compras) {
       this.idfuncionario = idfuncionario;
       this.nomefuncionario = nomefuncionario;
       this.cargofuncionario = cargofuncionario;
       this.emailcontato = emailcontato;
       this.telefone = telefone;
       this.celular = celular;
       this.criacaofuncionario = criacaofuncionario;
       this.pagamentos = pagamentos;
       this.vendas = vendas;
       this.recebimentos = recebimentos;
       this.compras = compras;
    }
   
    public int getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public String getNomefuncionario() {
        return this.nomefuncionario;
    }
    
    public void setNomefuncionario(String nomefuncionario) {
        this.nomefuncionario = nomefuncionario;
    }
    public String getCargofuncionario() {
        return this.cargofuncionario;
    }
    
    public void setCargofuncionario(String cargofuncionario) {
        this.cargofuncionario = cargofuncionario;
    }
    public String getEmailcontato() {
        return this.emailcontato;
    }
    
    public void setEmailcontato(String emailcontato) {
        this.emailcontato = emailcontato;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getCriacaofuncionario() {
        return this.criacaofuncionario;
    }
    
    public void setCriacaofuncionario(Date criacaofuncionario) {
        this.criacaofuncionario = criacaofuncionario;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getRecebimentos() {
        return this.recebimentos;
    }
    
    public void setRecebimentos(Set recebimentos) {
        this.recebimentos = recebimentos;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


